server:
  port: 9005

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AjinkyaPatil-hub/config-server
          default-label: main
          clone-on-start: true
  application:
    name: config-server