
spring:
  datasource:
   url: jdbc:mysql://localhost:3000/emp_db
   username: root
   password: root123
   driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   properties:
      hibernate:
       show_sql: true
#      ddl-auto: update