# all configuration is loaded from git hub repo named as application-product-service.yaml
spring:
  config:
    import:
    - optional:configserver:http://localhost:9005
    
  profiles:
    active:
    - review-service
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*" 